layout=seekbar
seekbar_height=small

#color of the cache ranges on the seekbar
seekbar_cache_color=#AED9ED
#color of the seekbar progress
seekbarfg_color=#DDDDDD
#color of the remaining seekbar
seekbarbg_color=#999999
#color of the seekbar handle
seek_handle_color=#AAAAAA
#color of the seekbar handle border
seek_handle_border_color=#BBBBBB
