live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#819AFF"
cyan = "#66D9EF"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F8F8F2"
yellow = "#E2E22E"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#333333"
blue = "#6A7EC8"
cyan = "#56ADBC"
green = "#86B42B"
magenta = "#8C6BC8"
red = "#C4265E"
white = "#E3E3DD"
yellow = "#B3B42B"

[colors.primary]
background = "#000000"
foreground = "#F8F8F2"

[colors.selection]
background = "#4B4B4B"
text = "#BBBBBB"

[cursor]
style = "Beam"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0018^"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018$"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = false
startup_mode = "Fullscreen"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
